import JSZip from 'jszip';

export const downloadProject = async (code: string, name: string = 'landing-page') => {
  const zip = new JSZip();

  // 1. Add the main generated file
  zip.file("src/App.tsx", code);

  // 2. Add a basic entry point
  zip.file("src/index.tsx", `
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
  `);

  // 3. Add Tailwind CSS file
  zip.file("src/index.css", `
@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  background-color: #09090b;
  color: #fff;
}
  `);

  // 4. Add index.html
  zip.file("public/index.html", `
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta name="description" content="Generated by Capsule.ai" />
    <title>Generated Landing Page</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
  </body>
</html>
  `);

  // 5. Add tsconfig.json to ensure TypeScript works correctly
  zip.file("tsconfig.json", JSON.stringify({
    "compilerOptions": {
      "target": "es5",
      "lib": [
        "dom",
        "dom.iterable",
        "esnext"
      ],
      "allowJs": true,
      "skipLibCheck": true,
      "esModuleInterop": true,
      "allowSyntheticDefaultImports": true,
      "strict": false,
      "noImplicitAny": false,
      "forceConsistentCasingInFileNames": true,
      "noFallthroughCasesInSwitch": true,
      "module": "esnext",
      "moduleResolution": "node",
      "resolveJsonModule": true,
      "isolatedModules": true,
      "noEmit": true,
      "jsx": "react-jsx"
    },
    "include": [
      "src"
    ]
  }, null, 2));

  // 6. Add tailwind.config.js
  zip.file("tailwind.config.js", `
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
  `);

  // 7. Add package.json
  zip.file("package.json", JSON.stringify({
    name: name,
    version: "0.1.0",
    private: true,
    dependencies: {
      "react": "^18.2.0",
      "react-dom": "^18.2.0",
      "framer-motion": "^10.16.4",
      "lucide-react": "^0.292.0",
      "clsx": "^2.0.0",
      "tailwind-merge": "^2.0.0",
      "web-vitals": "^2.1.0"
    },
    devDependencies: {
      "typescript": "^4.9.5",
      "@types/react": "^18.2.0",
      "@types/react-dom": "^18.2.0",
      "@types/node": "^16.7.13",
      "tailwindcss": "^3.3.0",
      "react-scripts": "5.0.1"
    },
    scripts: {
      "start": "react-scripts start",
      "build": "react-scripts build",
      "test": "react-scripts test",
      "eject": "react-scripts eject"
    },
    browserslist: {
      "production": [
        ">0.2%",
        "not dead",
        "not op_mini all"
      ],
      "development": [
        "last 1 chrome version",
        "last 1 firefox version",
        "last 1 safari version"
      ]
    }
  }, null, 2));

  // Generate the blob
  const content = await zip.generateAsync({ type: "blob" });
  
  // Trigger download
  const url = URL.createObjectURL(content);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${name}.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};